version: '3.5'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb-discussion
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: taskforce-discussion
    ports:
      - 27021:27017
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-discussion
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/

  taskforce.discussion:
    image: taskforce.discussion
    depends_on:
      - mongodb
      - mongodb-express
    container_name: taskforce.discussion.service
    ports:
      - 1002:3333
    environment:
      MONGO_DB: taskforce_discussions
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: test
      MONGO_AUTH_BASE: admin
