version: '3.5'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "taskforce-task"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  taskforce.task:
    image: taskforce.task
    depends_on:
      - postgres
    container_name: taskforce.task.service
    ports:
      - 1004:3333
    environment:
      DATABASE_URL: "postgresql://admin:test@postgres:5432/taskforce-task"
      RABBIT_USER: admin
      RABBIT_PASSWORD: test
      RABBIT_HOST: localhost
      RABBIT_PORT: 5672
      RABBIT_TASKS_SERVICE_QUEUE: taskforce.subscribers
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
