FROM node:16-alpine3.16
WORKDIR /app
COPY ./dist/apps/task .
RUN npm install --omit=dev
RUN npm prune --omit=dev
RUN npx prisma generate --schema ./assets/prisma/schema.prisma
CMD ["node", "./main.js"]
