GET http://localhost:3333/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E1OTFlMDI1MTE4NDJjY2ZmMDI5YWYiLCJlbWFpbCI6InVzZXJAdXNlcnMuY29tIiwicm9sZSI6IlBlcmZvcm1lciIsImZpcnN0bmFtZSI6IkFuZHJleSIsImxhc3RuYW1lIjoiUGV0cm92IiwiYXV0aElkIjoiNjNjMWQxNTBlMmFmNDljMWYyYWQ3NzllIiwiaWF0IjoxNjczNjQ2NDE2LCJleHAiOjE2NzM2NDcwMTZ9.354_vlyl5nk_zAjvaySVW9XsCBgU6IUh_4y1fwIz_CI

###
GET http://localhost:3333/api/categories/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E1OTFlMDI1MTE4NDJjY2ZmMDI5YWYiLCJlbWFpbCI6InVzZXJAdXNlcnMuY29tIiwicm9sZSI6IlBlcmZvcm1lciIsImZpcnN0bmFtZSI6IkFuZHJleSIsImxhc3RuYW1lIjoiUGV0cm92IiwiYXV0aElkIjoiNjNjMWQxNTBlMmFmNDljMWYyYWQ3NzllIiwiaWF0IjoxNjczNjQ2NDE2LCJleHAiOjE2NzM2NDcwMTZ9.354_vlyl5nk_zAjvaySVW9XsCBgU6IUh_4y1fwIz_CI

###
POST http://localhost:3333/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E1OTFlMDI1MTE4NDJjY2ZmMDI5YWYiLCJlbWFpbCI6InVzZXJAdXNlcnMuY29tIiwicm9sZSI6IlBlcmZvcm1lciIsImZpcnN0bmFtZSI6IkFuZHJleSIsImxhc3RuYW1lIjoiUGV0cm92IiwiYXV0aElkIjoiNjNjMWQxNTBlMmFmNDljMWYyYWQ3NzllIiwiaWF0IjoxNjczNjQ2NDE2LCJleHAiOjE2NzM2NDcwMTZ9.354_vlyl5nk_zAjvaySVW9XsCBgU6IUh_4y1fwIz_CI
Content-Type: application/json

{
  "title": "Программирование"
}

###
PUT http://localhost:3333/api/categories/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E1OTFlMDI1MTE4NDJjY2ZmMDI5YWYiLCJlbWFpbCI6InVzZXJAdXNlcnMuY29tIiwicm9sZSI6IlBlcmZvcm1lciIsImZpcnN0bmFtZSI6IkFuZHJleSIsImxhc3RuYW1lIjoiUGV0cm92IiwiYXV0aElkIjoiNjNjMWQxNTBlMmFmNDljMWYyYWQ3NzllIiwiaWF0IjoxNjczNjQ2NDE2LCJleHAiOjE2NzM2NDcwMTZ9.354_vlyl5nk_zAjvaySVW9XsCBgU6IUh_4y1fwIz_CI
Content-Type: application/json

{
  "title": "Аутсорсинг"
}

###
DELETE http://localhost:3333/api/categories/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E1OTFlMDI1MTE4NDJjY2ZmMDI5YWYiLCJlbWFpbCI6InVzZXJAdXNlcnMuY29tIiwicm9sZSI6IlBlcmZvcm1lciIsImZpcnN0bmFtZSI6IkFuZHJleSIsImxhc3RuYW1lIjoiUGV0cm92IiwiYXV0aElkIjoiNjNjMWQxNTBlMmFmNDljMWYyYWQ3NzllIiwiaWF0IjoxNjczNjQ2NDE2LCJleHAiOjE2NzM2NDcwMTZ9.354_vlyl5nk_zAjvaySVW9XsCBgU6IUh_4y1fwIz_CI

###
