POST http://localhost:3333/api/reviews/user/63c2bd422b90eaf8f6d3be8b/task/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E4YWE3MjcyYzQ5YjM5Y2U4NjE3ZjIiLCJlbWFpbCI6ImN1c3RvbWVyQGN1c3RvbWVyLmNvbSIsInJvbGUiOiJDdXN0b21lciIsImZpcnN0bmFtZSI6IjIyMjIyMjIyMiIsImxhc3RuYW1lIjpudWxsLCJhdXRoSWQiOiI2M2MyYzgwM2MwMTAyYmJmYzkzNWQzMGEiLCJpYXQiOjE2NzM3MDk1NzEsImV4cCI6MTY3MzcxMDE3MX0.5pNnVGlxxfnObthMQo7oeQKXYsBPnVqWcabaqpjyAvQ
Content-Type: application/json

{
  "review": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "score": 4
}

###
GET http://localhost:3333/api/reviews/user/63c2bd422b90eaf8f6d3be8b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E4YWE3MjcyYzQ5YjM5Y2U4NjE3ZjIiLCJlbWFpbCI6ImN1c3RvbWVyQGN1c3RvbWVyLmNvbSIsInJvbGUiOiJDdXN0b21lciIsImZpcnN0bmFtZSI6IjIyMjIyMjIyMiIsImxhc3RuYW1lIjpudWxsLCJhdXRoSWQiOiI2M2MyYzgwM2MwMTAyYmJmYzkzNWQzMGEiLCJpYXQiOjE2NzM3MDk1NzEsImV4cCI6MTY3MzcxMDE3MX0.5pNnVGlxxfnObthMQo7oeQKXYsBPnVqWcabaqpjyAvQ

###
